apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: lzmaurywehzexznjan/proxy:{{ .Values.version }}
          name: proxy
          ports:
            - containerPort: 8000
