apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MOVIE_DB_PASSWORD: bW92aWVfZGJfcGFzc3dvcmQ=
  MOVIE_DB_URI: cG9zdGdyZXNxbDovL21vdmllX2RiX3VzZXJuYW1lOm1vdmllX2RiX3Bhc3N3b3JkQG1vdmllLWRiL21vdmllX2RiX2Rldg==
  CAST_DB_PASSWORD: Y2FzdF9kYl9wYXNzd29yZA==
  CAST_DB_URI: cG9zdGdyZXNxbDovL2Nhc3RfZGJfdXNlcm5hbWU6Y2FzdF9kYl9wYXNzd29yZEBjYXN0LWRiL2Nhc3RfZGJfZGV2
