apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-db
  serviceName: movie-db
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: postgres:12.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MOVIE_DB_PASSWORD
                  name: secrets
          envFrom:
            - configMapRef:
                name: config-movie-db
          volumeMounts:
            - name: volume-data
              mountPath: /var/lib/postgresql/data/
          ports:
            - containerPort: 5432
  volumeClaimTemplates:
    - metadata:
        name: volume-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi